name: Semantic Pull Request
on: [pull_request]

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@91682d0665e8bfa4d6e4d735b8e5b8f95e8bb40e # v4.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          validateSingleCommit: true
