name: Check versions
on:
  issues:
    types: [opened, edited]

jobs:
  check-versions:
    if: ${{ github.event.label.name == 'bug' }}
    runs-on: ubuntu-latest
    steps:
      - uses: react-navigation/check-versions-action@deac0a1055b7b2c4b8f0b7a5b726d4b7c96d0c8e # v1.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          required-packages: |
            react-native-paper
          optional-packages: |
            @react-native-vector-icons/material-design-icons
